### ISSUE TITLE
Saving of settings on the web

### ISSUE THREAD

**Issue by Michael21107** [SuperPyroManiac/LSPDFR-Helper#33]
Refreshing the page or saving the same settings multiple times resets right or left (maybe even both) values seemingly randomly, which may result in a setting being reset, would both the selected value and current value of a setting be ''unset'', even when the user only wanted to change another one.
![image](https://github.com/user-attachments/assets/f89ce4bc-5a3a-4036-9558-8d036cf7fe16)

**Comment by SuperPyroManiac** [comment]
This will be fixed on the next update  - along with the ability to manually type a channel ID in the box / auto complete.

**Comment by SuperPyroManiac** [comment]
Fixed in dev build. This should be live either tonight or Friday.
