### ISSUE TITLE
Message always edited

### ISSUE THREAD

**Issue by Michael21107** [SuperPyroManiac/LSPDFR-Helper#4]
the autohelper ''menu'' message is always edited (got discord's ''edited'') tag despite being just created

**Comment by SuperPyroManiac** [comment]
Yeah, because it is differed then edited. Discord allows 3 seconds before it says interaction failed if I do not respond, so I make a deferred response to keep the loading spinner from timing out. Once the log is processed, I then edit that original message to the actual one you see.

**Comment by Michael21107** [comment]
you know i mean this?
![image](https://github.com/user-attachments/assets/7f7d88eb-de1a-4266-95c7-b6591cf0e96c)

**Comment by SuperPyroManiac** [comment]
That one shows the tag because I actually have edited it. I can change that text and it'll apply to all servers. Instead of resending the message I just edit them so the channel does not appear as unread.
