### ISSUE TITLE
Outdated plugins not detected

### ISSUE THREAD

**Issue by Michael21107** [SuperPyroManiac/LSPDFR-Helper#42]
[This log](https://github.com/user-attachments/files/18249530/RagePluginHook.log) includes outdated `ClearTheWay` and `686Callouts`, which however wasn't detected by the bot ([case w2pv1nrp](https://discord.com/channels/736140566311600138/1321639748082729062)).

**Comment by SuperPyroManiac** [comment]
Turns out this was due to LSPDFR caching issues. Works fine, not an issue.
