### ISSUE TITLE
Bot (DB) Editor only with selected server

### ISSUE THREAD

**Issue by Michael21107** [SuperPyroManiac/LSPDFR-Helper#50]
Editors can only access the Bot (DB) Editor after selecting a server.

**Comment by SuperPyroManiac** [comment]
Yeah I know I mentioned this when I added you all to it saying I do not have a system to support it otherwise yet

**Comment by Michael21107** [comment]
@SuperPyroManiac I remember something, just wanted to ''log'' it somewhere for you.
